CarPool/CarPool/Models/Route.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;



namespace CarPool.Models
{
    [Table("route")]
    public class Route
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        public AppUser CreatedBy { get; set; }

        public IList<RouteUser> RouteUser { get; set; }


        [Column("startdestination")]
        [Required(ErrorMessage ="Zadej misto odkud chces jet")]
        public string startDestination { get; set; }

        [Column("finaldestination")]
        [Required(ErrorMessage = "Zadej misto kam chces jet")]
        public string finalDestination { get; set; }

        [Column("date")]
        [Required(ErrorMessage = "Zadej datum")]
        public DateTime date { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Zadej cas")]
        public virtual DateTime time { get; set; }

        [Column("seats")]
        [Required(ErrorMessage = "Zadej pocet osob")]
        public int seats { get; set; }

        [Column("price")]
        public double price { get; set; }

       /* [Column("CreatedBy")]
        public string createdBy { get; set; }
        */
        [NotMapped]
        public virtual bool? connected { get; set; } = false;

    }
}

CarPool/CarPool/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using CarPool.Data;
using CarPool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace CarPool.Controllers
{
    public class RouteController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;
        private readonly ApplicationDbContext _db;

        public RouteController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, ApplicationDbContext db)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this._db = db;
        }



        [Route("/")]
        [Route("/Find")]
        [Route("/Home/Index")]
        public IActionResult FindRouteForm(Route r, string ReturnUrl)
        {
            ModelState.Clear(); // zamezi zobrazeni validačni hlašky po prvním spuštení
                                //  return View("Clear");

            return View("FindRouteForm");
        }


        [HttpGet]
        public IActionResult FindRoute(Route route)
        {

            if (!ModelState.IsValid)
                return View("FindRouteForm");

            route.date = route.date.Add(route.time.TimeOfDay);


            List<Route> routes = new List<Route>();
            Route r = new Route();





            var query = from ro in _db.routes
                        where route.startDestination == ro.startDestination && route.finalDestination == ro.finalDestination && ro.CreatedBy.Id != userManager.GetUserId(User)
                        select ro;

            //Select route is 1h horizont
            foreach (Route routeFromQuery in query)
            {
                if (route.date.AddMinutes(-30).Ticks <= routeFromQuery.date.Ticks && routeFromQuery.date.Ticks <= route.date.AddMinutes(30).Ticks)
                    routes.Add(routeFromQuery);
            }

            //Mark allready joined routes
            var selectedroutes = _db.routeUsers.Where(ru => ru.UserId == userManager.GetUserId(User));
            foreach (RouteUser selrout in selectedroutes)
            {
                selrout.Route.connected = true;
            }




            ViewData["Routes"] = routes;
            ViewData["Title"] = "Nalezené jízdy";
            if (routes.Count == 0)
                TempData["EmptyErrMessage"] = "Nebyly nalezeny žadné jízdy";
            //   ViewBag.FindingRoute = route;


            return View("FindRouteResolutTable");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddRouteToDB(Route route)
        {
            route.date = route.date.Add(route.time.TimeOfDay);
            route.CreatedBy = _db.Users.Where(u => u.Id == userManager.GetUserId(User)).FirstOrDefault();
            _db.routes.Add(route);
            _db.SaveChanges();

            return View("AddRouteNextStep");
        }


        [Route("/Create")]
        [Authorize]
        public IActionResult CreateRouteForm()
        {

            ViewData["UsersCars"] = _db.cars.Where(c => c.AppUser.Id == userManager.GetUserId(User)).ToList();
            ViewData["Message"] = "Your application description page.";

            if ((ViewData["UsersCars"] as List<Car>).Count == 0)
            {
                TempData["msg-error"] = "Nejprve si musite v sekci moje vozidla pridat automobil";
            }

            return View();
        }


        [Route("/Route/ShowDetail")]
        public IActionResult ShowDetail(int id)
        {
            ViewData["Message"] = "Your application description page.";
            Route routeFromDb = new Route();
            routeFromDb = _db.routes.Where(r => r.id == id).FirstOrDefault();
            return View(routeFromDb);
        }

        [Authorize]
        [HttpPost]
        [Route("/Route/JoinRoute")]
        public string JoinRoute(int id)
        {
            Route routeFromDB = new Route();
            routeFromDB = _db.routes.Where(r => r.id == id).FirstOrDefault();
            if (routeFromDB != null)
            {
                //try if exists
                RouteUser exists = _db.routeUsers.Where(ru => ru.RouteId == id && ru.UserId == userManager.GetUserId(User)).FirstOrDefault();
                if (routeFromDB.seats > 0 && exists==null)
                {
                    routeFromDB.seats--;
                    _db.SaveChanges();
                    _db.routeUsers.Add(new RouteUser { RouteId = id, UserId = userManager.GetUserId(User) });
                    _db.SaveChanges();
                }
                else
                {
                    TempData["msg-error"] = "Tato jízda je již plná";
                }
                
            }
            return "OK";
        }

        [Authorize]
        [HttpPost]
        [Route("/Route/LeaveRoute")]
        public string LeaveRoute(int id)
        {
            var routeTodelete = _db.routeUsers.Where(ru => ru.RouteId == id && ru.UserId == userManager.GetUserId(User)).FirstOrDefault();
            if (routeTodelete != null)
            {

                Route r = _db.routes.Where(ro => ro.id == id).FirstOrDefault();
                r.seats++;

                _db.routeUsers.Remove(routeTodelete);
                _db.SaveChanges();
            }
            else
                TempData["msg-error"] = "Došlo k chybě při odhlašování";
            return "OK";
        }

        [Authorize]
        [Route("/Route/Logged")]
        public IActionResult ShowLoggedRoutes()
        {
            List<Route> myRoutes = new List<Route>();



            var query = from RouteUser in _db.routeUsers
                        join route in _db.routes on RouteUser.RouteId equals route.id
                        where RouteUser.UserId == userManager.GetUserId(User) && route.id == RouteUser.RouteId
                        select route;


            foreach (Route routeFromQuery in query)
            {
                routeFromQuery.connected = true;
                myRoutes.Add(routeFromQuery);
            }



            ViewData["Routes"] = myRoutes;
            ViewData["Title"] = "Přihlášené jízdy";

            if (myRoutes.Count == 0)
                TempData["EmptyErrMessage"] = "Dosud nejsi přihlášen k žadné jízdě";


            return View("FindRouteResolutTable");

        }

        [Authorize]
        [Route("/Route/My")]
        public IActionResult ShowMyRoutes()
        {
            List<Route> createtByUser = new List<Route>();


            var query = _db.routes.Where(r => r.CreatedBy.Id == userManager.GetUserId(User));

            foreach (Route route in query)
            {
                route.connected = null;
                createtByUser.Add(route);
            }

            ViewData["Routes"] = createtByUser;
            ViewData["Title"] = "Vytvořené jízdy";

            if (createtByUser.Count == 0)
                TempData["EmptyErrMessage"] = "Dosud jsi nenabídl žádné jízdy";

            return View("FindRouteResolutTable");

        }

        [Authorize]
        [Route("/Route/Delete")]
        [HttpPost]
        public void DeleteRoute(int id)
        {


            Route ro = new Route();
            ro = _db.routes.Where(r => r.id == id && r.CreatedBy.Id == userManager.GetUserId(User)).FirstOrDefault();

            if (ro != null)
            {

                var routesToDelete = _db.routeUsers.Where(r => r.RouteId == id);
                foreach (RouteUser ru in routesToDelete)
                {
                    _db.Remove(ru);
                }


                ro = _db.routes.Where(r => r.id == id && r.CreatedBy.Id == userManager.GetUserId(User)).FirstOrDefault();
                _db.routes.Remove(ro);
                _db.SaveChanges();
            }
            else
            {
                TempData["msg-error"] = "Nastala chyba při mazaní jízdy";
            }



        }


    }
}

CarPool/CarPool/Views/Route/AddRouteNextStep.cshtml
<h1>Jizda byla úspěšně vytvořena</h1>



<a href="/Create" class="btn btn-primary"> Vytvořit další jízdu </a>
<a href="/Route/My" class="btn btn-primary"> Zobrazit všchny vytvořené jízdy </a>

CarPool/CarPool/Views/Route/CreateRouteForm.cshtml
@using CarPool.Models;
@section Scripts{
    <script src="~/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/GeoInput.js"></script>
    <script src="~/js/DateTimePicker.js"></script>

}

@section CSS{
    <link rel="stylesheet" href="~/lib/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" href="~/css/HomePage.css" />
}

@model Route

<partial name="_Messages" />

<h1>Vytvořit jízdu</h1>


<form asp-controller="Route" asp-action="AddRouteToDB" method="post">


    <div class="row mt-3">
        <div class="col-sm-8">
            <div class="input-group mb-1 ">
                <div class="input-group-prepend">
                    <span class="input-group-text same-width">Odkud</span>
                </div>
                <input id="start" asp-for="@Model.startDestination" class="form-control focusSelect adress_inp" placeholder="zadejte alepon tři znaky" autocomplete="off" data-target="input-Sorce-Content">
            </div>
            <span class="text-danger" asp-validation-for="@Model.startDestination"> </span>
            <div id="input-Sorce-Content" class="list-group d-none position-absolute ml-md-5 hiddenDiv">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>

    <div>

        <div class="row mt-2">
            <div class="col-sm-8">
                <div class="input-group mb-1 ">
                    <div class="input-group-prepend ">
                        <span class="input-group-text same-width">Kam</span>
                    </div>

                    <input asp-for="@Model.finalDestination" class="form-control focusSelect adress_inp" placeholder="zadejte alepon tři znaky" autocomplete="off" data-target="input-Destination-Content">
                </div>
                <span class="text-danger" asp-validation-for="@Model.finalDestination"> </span>
                <div id="input-Destination-Content" class="list-group d-none position-absolute ml-md-5 hiddenDiv">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <label for="date">Datum:</label>
            <div class="input-group mb-1 ">
                <div class="input-group-prepend ">
                    <div class="input-group-text"><span class="fa fa-calendar"></span></div>
                </div>
                <input id="date" asp-for="@Model.date" type="text" class="form-control dateinput">
            </div>
            <span class="text-danger" asp-validation-for="@Model.date"> </span>
        </div>

        <div class="col-sm-4">
            <label for="time">Čas:</label>
            <div class="input-group mb-1 ">
                <div class="input-group-prepend ">
                    <div class="input-group-text"><span class="fa fa-clock"></span></div>
                </div>
                <input id="time" asp-for="@Model.time" type="text" class="form-control timeinput">
            </div>
            <span class="text-danger" asp-validation-for="@Model.time"> </span>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="count">Počet míst</label>
                <select asp-for="@Model.seats" class="form-control" id="seats">
                    @if ((ViewData["UsersCars"] as List<Car>).Count() != 0)
                    {
                        @for (int i = 1; i <= (ViewData["UsersCars"] as List<Car>).First().seats; i++)
                        {
                            <option>@i</option>
                        }
                    }
                    else
                    {
                        <option>0</option>
                    }
                </select>
            </div>
            <span class="text-danger" asp-validation-for="@Model.seats"> </span>
        </div>

        <div class="col-sm-4">
            <div class="form-group">
                <label for="Car">Auto</label>
                <select asp-for="@Model.seats" class="form-control" id="carSelect">
                    @foreach (Car c in ViewData["UsersCars"] as List<Car>)
                    {
                        <option id="@c.id">@c.brand @c.model</option>
                    }
                </select>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-3">
            <button type="submit" class="btn btn-primary mt-4 ">Vytvořit</button>
        </div>
    </div>

</form>


<script src="~/lib/jquery/jquery.min.js"></script>
<script>
    $('#carSelect').on("change", function (event) {
        console.log("carid: " +$('option:selected', this).attr('id'));

        $.ajax({
            url: "/Car/GetSeats",
            type: "POST",
            data: "id=" + $('option:selected', this).attr('id'),
            success: function (response) {
                $('#seats').html(response);

            }
        });


    });


</script>

CarPool/CarPool/Views/Route/FindRouteForm.cshtml
@using CarPool.Models;
@section Scripts{
    <script src="~/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/GeoInput.js"></script>
    <script src="~/js/DateTimePicker.js"></script>


}

@section CSS{
    <link rel="stylesheet" href="~/lib/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" href="~/css/HomePage.css" />
}

@model Route

@{
    ViewData["Title"] = "Home Page";
}

<h1>Najít jízdu</h1>

<form asp-controller="Route" asp-action="FindRoute" method="get">
    <div>

        <div class="row">
            <div class="col-sm-8">

                <div class="input-group mb-2 ">
                    <div class="input-group-prepend ">
                        <span class="input-group-text">Odkud</span>
                    </div>
                    <input asp-for="@Model.startDestination" class="form-control focusSelect adress_inp" placeholder="zadejte alepon tři znaky" autocomplete="off" data-target="input-Sorce-Content" onkeyup="doSearch(this.value)">
                </div>
                <span class="text-danger" asp-validation-for="@Model.startDestination"> </span>
                <div id="input-Sorce-Content" class="list-group d-none position-absolute ml-md-5 hiddenDiv">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>

        <div>


            <div class="row">
                <div class="col-sm-8">
                    <div class="input-group mb-1 ">
                        <div class="input-group-prepend ">
                            <span class="input-group-text">Kam</span>
                        </div>
                        <input asp-for="@Model.finalDestination" class="form-control focusSelect adress_inp" placeholder="zadejte alepon tři znaky" autocomplete="off" data-target="input-Destination-Content">
                    </div>
                    <span class="text-danger" asp-validation-for="@Model.finalDestination"> </span>
                    <div id="input-Destination-Content" class="list-group d-none position-absolute ml-md-5 hiddenDiv">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <span>Datum:</span>
                <div class="input-group mb-1 ">
                    <div class="input-group-prepend ">
                        <div class="input-group-text"><span class="fa fa-calendar"></span></div>
                    </div>
                    <input asp-for="@Model.date" type="text" class="form-control dateinput" autocomplete="off">
                </div>
                <span class="text-danger" asp-validation-for="@Model.date"> </span>
            </div>

            <div class="col-sm-4">
                <span>Čas:</span>
                <div class="input-group mb-1 ">
                    <div class="input-group-prepend ">
                        <div class="input-group-text"><span class="fa fa-clock"></span></div>
                    </div>
                    <input asp-for="@Model.time" type="text" class="form-control timeinput" autocomplete="off">
                </div>
                <span class="text-danger" asp-validation-for="@Model.time"> </span>
            </div>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-3">
            <button id="submit" type="submit" class="btn btn-primary mt-4 ">Vyhledat</button>
        </div>
    </div>


    <script src="~/lib/jquery/jquery.js"></script>


</form>

CarPool/CarPool/Views/Route/FindRouteResolutTable.cshtml
@using CarPool.Models;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager


<h1>@ViewData["Title"]</h1>
@{

    Microsoft.AspNetCore.Http.QueryString urlParam = Context.Request.QueryString;
    Microsoft.AspNetCore.Http.PathString path = Context.Request.Path;
}

@if (ViewData["Routes"] != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Datum</th>
                <th>Cas</th>
                <th>Odkud</th>
                <th>Kam</th>
                <th>Volná Místa</th>
                <th>Cena</th>
                <th>Detail</th>
                <th>Připojit se</th>


            </tr>
        </thead>
        <tbody>

            @foreach (Route routeFromDb in (List<Route>)ViewData["Routes"])
            {
                <tr>
                    <td>@routeFromDb.date.ToString("dd.MM.yyyy")</td>
                    <td>@routeFromDb.date.ToString("HH:mm")</td>
                    <td>@routeFromDb.startDestination</td>
                    <td>@routeFromDb.finalDestination</td>
                    <td id="freePlaces"><span>@routeFromDb.seats</span></td>
                    <td>@routeFromDb.price</td>
                    <td><a href="/Route/ShowDetail?id=@routeFromDb.id">Detail</a></td>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @if (routeFromDb.connected == false)
                        {
                            <td><a href="#" id="@routeFromDb.id" title="join">Připojit se</a></td>
                        }
                        else if (routeFromDb.connected == true)
                        {
                            <td><a href="#" id="@routeFromDb.id" title="leave">Odhlásit se</a></td>
                        }
                        else
                        {
                            <td><a href="#" id="@routeFromDb.id" title="delete">Smazat</a></td>
                        }
                    }
                    else
                    {
                        <td>
                            <a asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="@(path)@(urlParam)">Připojit se</a>
                        </td>
                    }

                </tr>

            }
        </tbody>
    </table>
}
else
{
    @if (TempData["EmptyErrMessage"] != null)
    {
        <div class="col-4 mx-auto mt-auto">
            <div class="card card-body mb-2 ,mt-5">
                @TempData["EmptyErrMessage"].ToString()
            </div>
        </div>
    }



}

<script src="~/lib/jquery/jquery.js"></script>
<script>

    $(document).on("click", 'a[title="join"]', function () {
        var link = $(this);

        $.ajax({
            url: "/Route/JoinRoute",
            type: "POST",
            data: { id: link.attr("id") },  //data send to controller
            success: function () {
                link.closest("tr").find("#freePlaces").find("span").text(parseInt(link.closest("tr").find("#freePlaces").text()) - 1);
                link.attr("title", "leave");
                link.text("Odhlásit se");

            }
        });
    });

    $(document).on("click", 'a[title="leave"]', function () {
        var link = $(this);

        $.ajax({ //send request to find city/street

            url: "/Route/LeaveRoute",
            type: "POST",
            data: { id: link.attr("id") },  //data send to controller
            success: function () {
                link.closest("tr").find("#freePlaces").find("span").text(parseInt(link.closest("tr").find("#freePlaces").text()) + 1);
                link.attr("title", "join");
                link.text("Přihásit se");

            }
        });
    });


    $('a[title="delete"]').click(function () {
        var link = $(this);

        $.ajax({ //send request to find city/street

            url: "/Route/Delete",
            type: "POST",
            data: { id: link.attr("id") },  //data send to controller
            success: function () {
                link.parent().parent().hide();

            }
        });
    });





</script>

CarPool/CarPool/Views/Route/ShowDetail.cshtml
@using CarPool.Models;

@model Route

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail jízdy</h1>

<p>
    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Datum:</span>   </div>
        <div class="col-4"> <span class="h2">@Model.date.ToString("dd.MM")</span>  </div>
    </div>

    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Čas odjezdu: </span>  </div>
        <div class="col-4"><span class="h2"> @Model.date.ToString("HH:mm") </span>  </div>
    </div>

    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Místo odjezdu </span>  </div>
        <div class="col-4"><span class="h2"> @Model.startDestination </span>  </div>
    </div>

    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Místo příjezdu: </span>  </div>
        <div class="col-4"><span class="h2"> @Model.finalDestination </span>  </div>
    </div>

    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Počet míst </span>  </div>
        <div class="col-4"><span class="h2"> @Model.seats </span>  </div>
    </div>

    <div class="row mt-2">
        <div class="col-4"> <span class="h2">Cena </span>  </div>
        <div class="col-4"><span class="h2"> @Model.price </span>  </div>
    </div>
</p>

CarPool/CarPool/Views/Route/ShowMyRoutes.cshtml
@using CarPool.Models;

<h1>@ViewData["Title"]</h1>

@if (TempData.Count == 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Datum</th>
                <th>Cas</th>
                <th>Odkud</th>
                <th>Kam</th>
                <th>Volná Místa</th>
                <th>Cena</th>
                <th>Detail</th>
                <th>Připojit se</th>


            </tr>
        </thead>
        <tbody>

            @foreach (Route routeFromDb in (List<Route>)ViewData["Routess"])
            {
                <tr>
                    <td>@routeFromDb.date.ToString("dd.MM.yyyy")</td>
                    <td>@routeFromDb.date.ToString("HH:mm")</td>
                    <td>@routeFromDb.startDestination</td>
                    <td>@routeFromDb.finalDestination</td>
                    <td>@routeFromDb.seats</td>
                    <td>@routeFromDb.price</td>
                    <td><a href="/Route/ShowDetail?id=@routeFromDb.id">Detail</a></td>
                    <td><a href="#" id="@routeFromDb.id" title="delete">Smazat</a></td>
                    }

                </tr>

            }
        </tbody>
    </table>
}
else
{

    <div class="col-4 mx-auto mt-auto">
        <div class="card card-body mb-2 ,mt-5">
            @TempData["EmptyErrMessage"].ToString()
        </div>
    </div>




}

<script src="~/lib/jquery/jquery.js"></script>
<script>


    $('a[title="delete"]').click(function () {
        var link = $(this);

        $.ajax({ //send request to find city/street

            url: "/Route/JoinRoute",
            type: "POST",
            data: { id: link.attr("id") },  //data send to controller
            success: function () {
                link.attr("title", "leave");
                link.text("Odhlásit se");
            }
        });
    });









</script>